### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by brandonros** [taicho/postgres-to-mongo#1]
What's the motivation behind this project? I'd be curious to hear about your use case.

**Comment by taicho** [comment]
@brandonros Good question. First of all, I'm surprised somebody has found this library already! How did you find it by chance?

That being said, the use case is pretty straightforward: I'm working on a large scale postgres to mongo migration (and entire refactor of the data model) and I wanted a way to not just migrate the data but be able to finely control the resulting shape and be able to leverage the pseudo-hierarchical nature of mongo creating sub-documents and sub-document arrays from disparate Postgres tables during migration. After some initial research, I found some tooling but nothing that either a) met my requirements or b) was free of cost. There were some "enterprise" grade product suites that of course have different adapters for different database types but the either seemed too costly IMO or weren't specific enough to my needs.
